Gradyear filter
softstuds/final-project pull request #47
Opened 2022-12-09 02:37 UTC by tejalreddy

Added a graduation year filter and made other misc changes to industry and tags dropdowns

2022-12-10 19:52 UTC, hxliu33 requested changes
overall good, j some minor things

2022-12-10 19:52 UTC, hxliu33 commented on client/components/Industry/IndustryButton.vue
> +        deselectLabel="Click to unselect"
- [ ] nit: standardize naming pascal case vs camel case

2022-12-10 19:52 UTC, hxliu33 commented on server/user/middleware.ts
> +  }
have we tested using grad year filtering yet to ensure this middleware works? i know we had some issues with this structure when we used it for creating a user

2022-12-10 23:06 UTC, tejalreddy commented on server/user/middleware.ts
> +  }
Fixed

2022-12-11 01:17 UTC, jasmine2000 approved these changes

2022-12-11 14:03 UTC, merged